### ISSUE TITLE
FeathersUI Integration

### ISSUE THREAD

**Issue by reyco1** [RonaldoSetzer/robotlegs-extensions-Palidor#3]
Could you demonstrate, or even better, set up an example of how Palidor would work with the Feathers StackScreenNavigator component? Thanks!

**Comment by reyco1** [comment]
@RonaldoSetzer is it doable?

**Comment by RonaldoSetzer** [comment]
Hi, @reyco1, don't worry, I will prepare an example to you soon.
If you have any doubt, please feel free to add me on **Skype**: _Ronaldo.Setzer_
